name: pdf_kit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  get: ^4.7.2
  permission_handler: ^12.0.1
  dartz: ^0.10.1
  
  external_path: ^2.2.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  open_filex: ^4.7.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  pdfx: ^2.9.2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  go_router: ^17.0.0
  provider: ^6.1.5+1
  pdf: ^3.11.3
  path: ^1.9.1
  signature: ^6.3.0
  image_picker: ^1.1.2
  
  flutter_image_compress: ^2.4.0
  ares_defence_labs_lock_smith_pdf: ^0.0.7
  pdf_combiner: ^4.4.1
  image: ^4.5.4
  reorderable_grid_view: ^2.2.8
  flutter_pdfview: ^1.4.3
  url_launcher: ^6.3.0
  device_info_plus: ^12.3.0
  firebase_core: ^4.3.0
  firebase_analytics: ^12.1.0
  firebase_crashlytics: ^5.0.6
  

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/l10n/
