name: pdf_kit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  get: ^4.7.2
  permission_handler: ^12.0.1
  dartz: ^0.10.1
  external_path: ^2.2.0
  path_provider: ^2.1.5
  mime: ^2.0.0
  open_filex: ^4.7.0
  intl: ^0.20.2
  pdfx: ^2.9.2
  share_plus: ^12.0.1
  shimmer: ^3.0.0
  go_router: ^17.0.0
  provider: ^6.1.5+1
  pdf: ^3.11.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
